# Generated by Django 5.0.1 on 2024-01-03 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='Crud',
        ),
    ]
